config/routes.rb
Album1::Application.routes.draw do
  resources :post_attachments

resources :posts
resources :post_attachments do
  get 'download', on: :member
end

resources :tags
resources :home

devise_for :users, :controllers => { omniauth_callbacks: "omniauth_callbacks" ,registrations: "registrations"}
  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
  def new
    
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<body>
	<div class="yard">
		<%= link_to'ABOUTUS',new_home_path%>
		</div>
		<br><br>
		<div class="yard">
		<%= link_to'MY ALBUMS',posts_path%>
		</div>
		<div>
		 <%= image_tag 'images65.jpeg',size: "160x100",:class=>'fish'%>
		 <%= image_tag 'index62.jpeg',size: "160x100",:class=>'fish'%>
		 <%= image_tag 'images62.jpeg',size: "160x100",:class=>'fish'%>
		 <%= image_tag 'images67.jpeg',size: "160x100",:class=>'fish'%>
		  <%= image_tag 'images68.jpeg',size: "160x100",:class=>'fish'%>
		   <%= image_tag 'images69.jpeg',size: "160x100",:class=>'fish'%>
		    <%= image_tag 'images45.jpeg',size: "160x100",:class=>'fish'%>
		    </div>
		    <p id='fish'>My picture ALBUM</P>
	</body>
<style>

.shipp
{
	background: white;
	display: inline;
	float: right;
	margin: 0 15px 30px;
	padding: 10px 10px 25px;
	text-align: center;
	text-decoration: none;
	-webkit-box-shadow: 0 4px 6px rgba(0, 0, 0, .3);
	-moz-box-shadow: 0 4px 6px rgba(0,0,0,.3);
	box-shadow: 0 4px 6px rgba(0,0,0,.3);
	-webkit-transition: all .15s linear;
	-moz-transition: all .15s linear;
	transition: all .15s linear;
	z-index:0;
        position:relative;
}
.yard
{
	background: white;
	display: inline;
	float: left;
	margin: 0 15px 30px;
	padding: 10px 10px 25px;
	text-align: center;
	text-decoration: none;
	-webkit-box-shadow: 0 4px 6px rgba(0, 0, 0, .3);
	-moz-box-shadow: 0 4px 6px rgba(0,0,0,.3);
	box-shadow: 0 4px 6px rgba(0,0,0,.3);
	-webkit-transition: all .15s linear;
	-moz-transition: all .15s linear;
	transition: all .15s linear;
	z-index:0;
        position:relative;
}
.fish
{
	background: white;
	display: inline;
	float: left;
	margin: 0 15px 30px;
	padding: 10px 10px 25px;
	text-align: center;
	text-decoration: none;
	-webkit-box-shadow: 0 4px 6px rgba(0, 0, 0, .3);
	-moz-box-shadow: 0 4px 6px rgba(0,0,0,.3);
	box-shadow: 0 4px 6px rgba(0,0,0,.3);
	-webkit-transition: all .15s linear;
	-moz-transition: all .15s linear;
	transition: all .15s linear;
	z-index:0;
        position:relative;
}
.fish:nth-child(2n)
{
	-webkit-transform: rotate(4deg);  
	-moz-transform: rotate(4deg); 
	transform: rotate(4deg); 
}
.fish:nth-child(3n) { 
	-webkit-transform: rotate(-24deg);  
	-moz-transform: rotate(-24deg); 
	transform: rotate(-24deg); 
}
.fish:nth-child(4n)
{
	-webkit-transform: rotate(14deg);  
	-moz-transform: rotate(14deg); 
	transform: rotate(14deg); 
}
.fish:nth-child(5n)
{
	-webkit-transform: rotate(-18deg);  
	-moz-transform: rotate(-18deg); 
	transform: rotate(-18deg); 
}
.fish:hover{
	-webkit-transform: rotate(0deg); 
	-moz-transform: rotate(0deg);
        transform: rotate(0deg);
	-webkit-transform: scale(1.2); 
	-moz-transform: scale(1.2);
        transform: scale(1.2);
	z-index:10;
	-webkit-box-shadow: 0 10px 20px rgba(0, 0, 0, .7);
	-moz-box-shadow: 0 10px 20px rgba(0,0,0,.7);
        box-shadow: 0 10px 20px rgba(0,0,0,.7);
}
.fish img { 
	display: block; 
	width: inherit; 
}
body {
    background-image: url("/assets/images37.jpeg");
   background-size: 1250px 850px;
   
} 
#fish {
  font: 400 100px/1.5 'Pacifico', Helvetica, sans-serif;
  color: #2b2b2b;
  text-shadow: 3px 3px 0px rgba(0,0,0,0.1), 7px 7px 0px rgba(0,0,0,0.05);
}
</style>

app/views/home/new.html.erb
<body>
	<div class="yard">
		
		<%= link_to'MY ALBUMS',posts_path%>
		</div>
		<br><br>
		 <%= image_tag 'images65.jpeg',size: "160x100",:class=>'fish'%>
		 <%= image_tag 'index62.jpeg',size: "160x100",:class=>'fish'%>
		 <%= image_tag 'images62.jpeg',size: "160x100",:class=>'fish'%>
		 <%= image_tag 'images67.jpeg',size: "160x100",:class=>'fish'%>
		  <%= image_tag 'images68.jpeg',size: "160x100",:class=>'fish'%>
		   <%= image_tag 'images69.jpeg',size: "160x100",:class=>'fish'%>
		    <%= image_tag 'images45.jpeg',size: "160x100",:class=>'fish'%>
		     
		    <p id='fish'>My picture ALBUM let's you cherish your  memories forever'</P>
		    	
		    	
	</body>
<style>

.shipp
{
	background: white;
	display: inline;
	float: right;
	margin: 0 15px 30px;
	padding: 10px 10px 25px;
	text-align: center;
	text-decoration: none;
	-webkit-box-shadow: 0 4px 6px rgba(0, 0, 0, .3);
	-moz-box-shadow: 0 4px 6px rgba(0,0,0,.3);
	box-shadow: 0 4px 6px rgba(0,0,0,.3);
	-webkit-transition: all .15s linear;
	-moz-transition: all .15s linear;
	transition: all .15s linear;
	z-index:0;
        position:relative;
}
.yard
{
	background: white;
	display: inline;
	float: left;
	margin: 0 15px 30px;
	padding: 10px 10px 25px;
	text-align: center;
	text-decoration: none;
	-webkit-box-shadow: 0 4px 6px rgba(0, 0, 0, .3);
	-moz-box-shadow: 0 4px 6px rgba(0,0,0,.3);
	box-shadow: 0 4px 6px rgba(0,0,0,.3);
	-webkit-transition: all .15s linear;
	-moz-transition: all .15s linear;
	transition: all .15s linear;
	z-index:0;
        position:relative;
}
.fish
{
	background: white;
	display: inline;
	float: left;
	margin: 0 15px 30px;
	padding: 10px 10px 25px;
	text-align: center;
	text-decoration: none;
	-webkit-box-shadow: 0 4px 6px rgba(0, 0, 0, .3);
	-moz-box-shadow: 0 4px 6px rgba(0,0,0,.3);
	box-shadow: 0 4px 6px rgba(0,0,0,.3);
	-webkit-transition: all .15s linear;
	-moz-transition: all .15s linear;
	transition: all .15s linear;
	z-index:0;
        position:relative;
}
.fish:nth-child(2n)
{
	-webkit-transform: rotate(4deg);  
	-moz-transform: rotate(4deg); 
	transform: rotate(4deg); 
}
.fish:nth-child(3n) { 
	-webkit-transform: rotate(-24deg);  
	-moz-transform: rotate(-24deg); 
	transform: rotate(-24deg); 
}
.fish:nth-child(4n)
{
	-webkit-transform: rotate(14deg);  
	-moz-transform: rotate(14deg); 
	transform: rotate(14deg); 
}
.fish:nth-child(5n)
{
	-webkit-transform: rotate(-18deg);  
	-moz-transform: rotate(-18deg); 
	transform: rotate(-18deg); 
}
.fish:hover{
	-webkit-transform: rotate(0deg); 
	-moz-transform: rotate(0deg);
        transform: rotate(0deg);
	-webkit-transform: scale(1.2); 
	-moz-transform: scale(1.2);
        transform: scale(1.2);
	z-index:10;
	-webkit-box-shadow: 0 10px 20px rgba(0, 0, 0, .7);
	-moz-box-shadow: 0 10px 20px rgba(0,0,0,.7);
        box-shadow: 0 10px 20px rgba(0,0,0,.7);
}
.fish img { 
	display: block; 
	width: inherit; 
}
body {
    background-image: url("/assets/index70.jpeg");
   background-size: 1250px 850px;
   
} 
#fish {
  font: 400 100px/1.5 'Pacifico', Helvetica, sans-serif;
  color: #2b2b2b;
  text-shadow: 3px 3px 0px rgba(0,0,0,0.1), 7px 7px 0px rgba(0,0,0,0.05);
}
</style>