config/routes.rb
Album1::Application.routes.draw do
  resources :post_attachments

resources :posts
resources :post_attachments do
  get 'download', on: :member
end

resources :tags
resources :home

devise_for :users, :controllers => { omniauth_callbacks: "omniauth_callbacks" ,registrations: "registrations"}
  root 'home#index'

end

app/models/post_attachment.rb
class PostAttachment < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :post
  has_and_belongs_to_many :tags
  accepts_nested_attributes_for :tags , allow_destroy: true
  before_save :assign_tags
 private
  def assign_tags
      self.tags = tags[0].name.split(',').map do |name|
        Tag.find_or_create_by_name(name)
      end
   end
   def previous_post
  self.class.first(:conditions => ["id < ?", id], :order => "id desc")
end

def next_post
  self.class.first(:conditions => ["id > ?", id], :order => "id asc")
end
 end
 

app/controllers/post_attachments_controller.rb
class PostAttachmentsController < ApplicationController
  #before_action :set_post_attachment, only: [:show, :edit, :update, :destroy]



  
  def index
    
    @post_attachments = PostAttachment.all
  end

 
  def show
    @post_attachment= PostAttachment.find(params[:id])
   send_file("#{@post_attachment.avatar}",
              type: "image/jpg",
              disposition: "attachment"
              )
  end

  
  def new
    @post_attachment = PostAttachment.new
  end

  
  def edit
    @post_attachment= PostAttachment.find(params[:id])
  end

  
 def create
    @post_attachment = PostAttachment.new(post_attachment_params)

    respond_to do |format|
      if @post_attachment.save
        format.html { redirect_to @post_attachment, notice: 'Image was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post_attachment }
      else
        format.html { render action: 'new' }
        format.json { render json: @post_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  
 def update
   @post_attachment= PostAttachment.find(params[:id])
  respond_to do |format|
    if @post_attachment.update(post_attachment_params)
      format.html { redirect_to @post_attachment.post, notice: 'Post attachment was successfully updated.' }
    end 
  end
end

  def destroy
      @post_attachment= PostAttachment.find(params[:id])
       @post_attachment.destroy
       redirect_to :back
    end
  
  def download
     
  end
  private
   
    #def set_post_attachment
     # @post_attachment = PostAttachment.find(params[:id])
    #end

    
    def post_attachment_params
      params.require(:post_attachment).permit(:post_id, :avatar,)
    end
  end

app/helpers/post_attachments_helper.rb
module PostAttachmentsHelper
  
end

app/views/post_attachments/_form.html.erb
<%= image_tag @post_attachment.avatar_url(:thumb)%>
<%= form_for(@post_attachment) do |f| %>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/post_attachments/edit.html.erb
<body>
<h1>Editing image</h1>

<%= render 'form' %>
<%= link_to 'Back', posts_path%>
</body>
<style>
body {
    background-image: url("/assets/images37.jpeg");
   background-size: 1250px 850px;
   
} 
</style>

app/views/post_attachments/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', post_attachments_path %>

app/views/post_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @post_attachment.post_id %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @post_attachment.avatar %>
</p>

<%= link_to 'Edit', edit_post_attachment_path(@post_attachment) %> |
<%= link_to 'Back', post_attachments_path %>