config/routes.rb
Album1::Application.routes.draw do
  resources :post_attachments

resources :posts
resources :post_attachments do
  get 'download', on: :member
end

resources :tags
resources :home

devise_for :users, :controllers => { omniauth_callbacks: "omniauth_callbacks" ,registrations: "registrations"}
  root 'home#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
belongs_to :user
has_many :post_attachments
accepts_nested_attributes_for :post_attachments , allow_destroy: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   def index
     
      @posts = Post.all
      @user =current_user
      
      
      
       respond_to do |format|
      format.html
      format.js
      end
      
   end
   def show
      @post = Post.find(params[:id])
      @post_attachments = @post.post_attachments.all
      @post_attachment = @post.post_attachments.first
      
       respond_to do |format|
      format.html{ render :layout => !request.xhr? }
      format.js
      end
      
   end
   def new
     
     @post = Post.new
     2.times do
     @post_attachment = @post.post_attachments.build
     @tag = @post_attachment.tags.build 
     end
     
   end
   def edit
     
     @post = Post.find(params[:id])
     @post_attachment = @post.post_attachments.build
     
    end
 

   def create
     @post = current_user.posts.new(post_params)
     if @post.save
       redirect_to @post
     else
       render action: 'new'
     end
     end
    def update
     
     @post = Post.find(params[:id])
     
    
        if @post.update(post_params)
          redirect_to @post
        else
          render 'edit'
        end
     end
     
     def destroy
       @post= Post.find(params[:id])
       @post.destroy
       redirect_to posts_path
  
     end
     
    private
  def post_params
    params.require(:post).permit(:title, :description, post_attachments_attributes: [:avatar ,tags_attributes: [:name]])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_posts.html.erb
<table>
  <tr>
    <th>Tilte</th>
    <th>Description</th>
  </tr>
 
  <% @user.posts.each do |post| %>
    <tr>
      <td><%= post.title%></td>
      <td><%= post.description %></td>
      <td><%= link_to 'Show',post_path(post),:remote => true,:id=>'c'%></td>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <td><%= button_to 'Delete', post, method: :delete,       
              data: { confirm: 'Are you sure?' }%></td> 
    </tr>
  <% end %>
</table>

app/views/posts/edit.html.erb
<body>
<h1>Editing album</h1>
 
<%= form_for :post, url: post_path(@post),:html => {:multipart => true},method: :patch do |f| %>
 
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this album from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <%= f.fields_for :post_attachments do |p| %>
 
       <%= p.label :avatar %><br>
       <%= p.file_field :avatar %>
       
   <% end %>
  <p>
    <%= f.submit %>
  </p>

<% end %>

  
<%= link_to 'Back', posts_path %>
 </body>
 <style>
 body {
    background-image: url("/assets/images37.jpeg");
   background-size: 1250px 850px;
   
} 
</style>

app/views/posts/index.html.erb
<h1 id='ij'>Listing Albums</h1>
<%= link_to 'New album', new_post_path ,:id=>'kk'%>
<div style="float:right;width:300px;>
<div id="container">
  <div id="butterfly">
    <div class="left wingg"></div>
    <div class="right wingg"></div>
    
  </div>
</div>
</div>
<div class='my'>
<body>

    
 
  <% @user.posts.each do |post| %>
  
   <div style="border-width: 4px;border-height: 10px; border-style: ridge; border-color: red; width: 100px;
    height: 80px;margin-top: 90px;" id='gf'> 
    <tr>
    	
    	<div id="hf">
      <b>Title-</b> <td><%= post.title%></td><br>
      <b>Description-</b> <td><%= post.description %></td><br>
     <div class="flower violet">
<div class="leaf tl"></div>
<div class="leaf tr"></div>
<div class="leaf bl"></div>
<div class="leaf br"></div>
</div>
       </tr>
       <table>
       	<tr>
     <th> <%= button_to 'Show',post_path(post),method: :get,:id=>'df'%></th>
      <th><%= button_to 'Edit', edit_post_path(post),method: :get,:id=>'df1' %></th>
    <th>  <%= button_to 'Delete', post, method: :delete,:id=>'df2',       
              data: { confirm: 'Are you sure?' }%></th>
   </tr>
   </table>
    
    </div>
    </div>
  <% end %>
</table>
</div>
<script>
$(document).ready(function(){
	
    $(".new").click(function(e){
    	e.preventDefault();
    
       var s=$(this).attr('href');
       alert(s);
          $.ajax({
          	
       	
       method: "GET",
     
      
       url: s,
       
       success: function(d) {
     
       	
       
 $(".my").html(d);
 
 
     
       
      
   }
    })
    
});
});
	</script>
</body>

<style>
#df {
    position: relative;
    padding: 1px 4px;
    margin: 35px 6px 10px 0px;
    float: left;
    border-radius: 10px;
    font-family: 'Helvetica', cursive;
    font-size: 25px;
    color: #FFF;
    text-decoration: none;  
    background-color: #3498DB;
    border-bottom: 5px solid #2980B9;
    text-shadow: 0px -2px #2980B9;
    /* Animation */
    transition: all 0.1s;
    -webkit-transition: all 0.1s;
}

#df:hover, 
#df:focus {
    text-decoration: none;
    color: #fff;
}
#df2 {
    position: relative;
    padding: 1px 1px;
    margin: 35px 6px 10px 0px;
    float: left;
    border-radius: 10px;
    font-family: 'Helvetica', cursive;
    font-size: 25px;
    color: #FFF;
    text-decoration: none;  
    background-color: #3498DB;
    border-bottom: 5px solid #2980B9;
    text-shadow: 0px -2px #2980B9;
    /* Animation */
    transition: all 0.1s;
    -webkit-transition: all 0.1s;
}

#df2:hover, 
#df2:focus {
    text-decoration: none;
    color: #fff;
}
#df1 {
    position: relative;
    padding: 1px 1px;
    margin: 35px 6px 10px 0px;
    float: left;
    border-radius: 10px;
    font-family: 'Helvetica', cursive;
    font-size: 25px;
    color: #FFF;
    text-decoration: none;  
    background-color: #3498DB;
    border-bottom: 5px solid #2980B9;
    text-shadow: 0px -2px #2980B9;
    /* Animation */
    transition: all 0.1s;
    -webkit-transition: all 0.1s;
}

#df1:hover, 
#df1:focus {
    text-decoration: none;
    color: #fff;
}
#hf {
  font: 70 40px/1.5 'Pacifico', Helvetica, sans-serif;
  color: #000033;
  text-shadow: 3px 3px 0px rgba(0,0,0,0.1), 7px 7px 0px rgba(0,0,0,0.05);
}
#ij {
  font: 100 60px/1.5 'Pacifico', Helvetica, sans-serif;
  color: #2b2b2b;
  text-shadow: 3px 3px 0px rgba(0,0,0,0.1), 7px 7px 0px rgba(0,0,0,0.05);
}
#kk {
  font: 100 40px/1.5 'Pacifico', Helvetica, sans-serif;
  color: #2b2b2b;
  text-shadow: 3px 3px 0px rgba(0,0,0,0.1), 7px 7px 0px rgba(0,0,0,0.05);
}
body {
    background-image: url("/assets/index0.jpeg");
   background-size: 1290px 650px;
   
} 
</style>

<style>
body{
  background-color: lightblue;
}

#container {
perspective: 600px;
perspective-origin: -20% 20%;
width: 850px;
height: 566px;
left: 300px;
top: 0px;
color: gray;
margin: 0px auto;
}

#butterfly {
 -webkit-animation: mymove 5s infinite; /* Chrome, Safari, Opera */
    animation: mymove 5s infinite;
transform: rotateZ(-30deg) rotate3d(0, 1, 0, 0deg) scale3d(0.5, 0.5, 0.5);
transform-origin: 51% 50%;
left: 0px;
top: 0px;
width: 400px;
height: 238px;
transform-style: preserve-3d;
/*Fly in a loop below*/
/*animation-name: butterflyani;
animation-duration: 5s;
animation-iteration-count: infinite;
animation-timing-function: linear;*/
}

.wingg {
transform: rotateX(30deg)  translate3d(-200px, 0px, 0px) rotate3d(0, 1, 0, 160deg);
transform-origin: top right;
position: absolute;
left: 200px;
top: 0px;
width: 200px;
height: 238px;
background: url(http://blueskyyogaohio.com/wp-content/themes/Chameleon/images/butterfly.png) no-repeat;
animation-name: rightwingani;
animation-duration: 0.6s;
animation-delay: 2s;
animation-iteration-count: infinite;
animation-timing-function: ease-out;
}

#butterfly .left{
transform: rotateX(30deg) rotate3d(0, 1, 0, 0deg);
animation-name: leftwingani;
left: 0px;
top: 0px;
}

@keyframes rightwingani {
	from {
		transform:rotateX(30deg) translate3d(-200px, 0px, 0px) rotate3d(0, 1, 0, 160deg);
	}
	50% {
		transform:rotateX(30deg) translate3d(-200px, 0px, 0px) rotate3d(0, 1, 0, 100deg);
	}
	to{
		transform:rotateX(30deg) translate3d(-200px, 0px, 0px) rotate3d(0, 1, 0, 160deg);
	}
}

@keyframes leftwingani {
	from {
		transform:rotateX(30deg) rotate3d(0, 1, 0, 0deg);
	}
	50% {
		transform:rotateX(30deg) rotate3d(0, 1, 0, 80deg);
	}
	to{
		transform:rotateX(30deg) rotate3d(0, 1, 0, 00deg);
	}
}

.flower.violet > .leaf {
  	background: #FF1493;
}
.leaf {
	width: 20px;
	height: 20px; 
	border-radius: 40px;
	float: left;
}

.tl {
	border-bottom-right-radius: 0px;
}

.tr {
	border-bottom-left-radius: 0px;
}

.bl {
	border-top-right-radius: 0px;
	clear: left;
}

.br {
	border-top-left-radius: 0px;
}

.flower {
	float: left;
}

.flower:hover {
	-webkit-animation: bubbly 1s ease-in;
	-moz-animation: bubbly 1s ease-in;
	-ms-animation: bubbly 1s ease-in;
	-o-animation: bubbly 1s ease-in;
	animation: bubbly 1s ease-in;
}

@keyframes "bubbly" {
 0% {
    -webkit-transform: scale(1,1) rotate(0deg);
   	-moz-transform: scale(1,1) rotate(0deg);
   	-o-transform: scale(1,1) rotate(0deg);
   	-ms-transform: scale(1,1) rotate(0deg);
   	transform: scale(1,1) rotate(0deg);
 }
 10% {
    -webkit-transform: rotate(5deg);
   	-moz-transform: rotate(5deg);
   	-o-transform: rotate(5deg);
   	-ms-transform: rotate(5deg);
   	transform: rotate(5deg);
 }
 20% {
    -webkit-transform: rotate(-5deg);
   	-moz-transform: rotate(-5deg);
   	-o-transform: rotate(-5deg);
   	-ms-transform: rotate(-5deg);
   	transform: rotate(-5deg);
 }
 30% {
    -webkit-transform: rotate(5deg);
   	-moz-transform: rotate(5deg);
   	-o-transform: rotate(5deg);
   	-ms-transform: rotate(5deg);
   	transform: rotate(5deg);
 }
 40% {
    -webkit-transform: scale(.7,.7) rotate(-5deg);
   	-moz-transform: scale(.7,.7) rotate(-5deg);
   	-o-transform: scale(.7,.7) rotate(-5deg);
   	-ms-transform: scale(.7,.7) rotate(-5deg);
   	transform: scale(.7,.7) rotate(-5deg);
 }
 50% {
    -webkit-transform: scale(1.2,1.2) rotate(5deg);
   	-moz-transform: scale(1.2,1.2) rotate(5deg);
   	-o-transform: scale(1.2,1.2) rotate(5deg);
   	-ms-transform: scale(1.2,1.2) rotate(5deg);
   	transform: scale(1.2,1.2) rotate(5deg);
 }
 60% {
    -webkit-transform: scale(.8,.8) rotate(-5deg);
   	-moz-transform: scale(.8,.8) rotate(-5deg);
   	-o-transform: scale(.8,.8) rotate(-5deg);
   	-ms-transform: scale(.8,.8) rotate(-5deg);
   	transform: scale(.8,.8) rotate(-5deg);
 }
 70% {
    -webkit-transform: scale(1.1,1.1) rotate(5deg);
   	-moz-transform: scale(1.1,1.1) rotate(5deg);
   	-o-transform: scale(1.1,1.1) rotate(5deg);
   	-ms-transform: scale(1.1,1.1) rotate(5deg);
   	transform: scale(1.1,1.1) rotate(5deg);
 }
 80% {
    -webkit-transform: scale(.9,.9) rotate(-5deg);
   	-moz-transform: scale(.9,.9) rotate(-5deg);
   	-o-transform: scale(.9,.9) rotate(-5deg);
   	-ms-transform: scale(.9,.9) rotate(-5deg);
   	transform: scale(.9,.9) rotate(-5deg);
 }
 90% {
    -webkit-transform: scale(1,1) rotate(5deg);
   	-moz-transform: scale(1,1) rotate(5deg);
   	-o-transform: scale(1,1) rotate(5deg);
   	-ms-transform: scale(1,1) rotate(5deg);
   	transform: scale(1,1) rotate(5deg);
 }
 100% {
    -webkit-transform: rotate(0deg);
   	-moz-transform: rotate(0deg);
   	-o-transform: rotate(0deg);
   	-ms-transform: rotate(0deg);
   	transform: rotate(0deg);
 }

}

@-moz-keyframes bubbly {
 0% {
   -moz-transform: scale(1,1) rotate(0deg);
   transform: scale(1,1) rotate(0deg);
 }
 10% {
   -moz-transform: rotate(5deg);
   transform: rotate(5deg);
 }
 20% {
   -moz-transform: rotate(-5deg);
   transform: rotate(-5deg);
 }
 30% {
   -moz-transform: rotate(5deg);
   transform: rotate(5deg);
 }
 40% {
   -moz-transform: scale(.7,.7) rotate(-5deg);
   transform: scale(.7,.7) rotate(-5deg);
 }
 50% {
   -moz-transform: scale(1.2,1.2) rotate(5deg);
   transform: scale(1.2,1.2) rotate(5deg);
 }
 60% {
   -moz-transform: scale(.8,.8) rotate(-5deg);
   transform: scale(.8,.8) rotate(-5deg);
 }
 70% {
   -moz-transform: scale(1.1,1.1) rotate(5deg);
   transform: scale(1.1,1.1) rotate(5deg);
 }
 80% {
   -moz-transform: scale(.9,.9) rotate(-5deg);
   transform: scale(.9,.9) rotate(-5deg);
 }
 90% {
   -moz-transform: scale(1,1) rotate(5deg);
   transform: scale(1,1) rotate(5deg);
 }
 100% {
   -moz-transform: rotate(0deg);
   transform: rotate(0deg);
 }

}

@-webkit-keyframes "bubbly" {
 0% {
   -webkit-transform: scale(1,1) rotate(0deg);
   transform: scale(1,1) rotate(0deg);
 }
 10% {
   -webkit-transform: rotate(5deg);
   transform: rotate(5deg);
 }
 20% {
   -webkit-transform: rotate(-5deg);
   transform: rotate(-5deg);
 }
 30% {
   -webkit-transform: rotate(5deg);
   transform: rotate(5deg);
 }
 40% {
   -webkit-transform: scale(.7,.7) rotate(-5deg);
   transform: scale(.7,.7) rotate(-5deg);
 }
 50% {
   -webkit-transform: scale(1.2,1.2) rotate(5deg);
   transform: scale(1.2,1.2) rotate(5deg);
 }
 60% {
   -webkit-transform: scale(.8,.8) rotate(-5deg);
   transform: scale(.8,.8) rotate(-5deg);
 }
 70% {
   -webkit-transform: scale(1.1,1.1) rotate(5deg);
   transform: scale(1.1,1.1) rotate(5deg);
 }
 80% {
   -webkit-transform: scale(.9,.9) rotate(-5deg);
   transform: scale(.9,.9) rotate(-5deg);
 }
 90% {
   -webkit-transform: scale(1,1) rotate(5deg);
   transform: scale(1,1) rotate(5deg);
 }
 100% {
   -webkit-transform: rotate(0deg);
   transform: rotate(0deg);
 }

}

@-ms-keyframes "bubbly" {
 0% {
   -ms-transform: scale(1,1) rotate(0deg);
   transform: scale(1,1) rotate(0deg);
 }
 10% {
   -ms-transform: rotate(5deg);
   transform: rotate(5deg);
 }
 20% {
   -ms-transform: rotate(-5deg);
   transform: rotate(-5deg);
 }
 30% {
   -ms-transform: rotate(5deg);
   transform: rotate(5deg);
 }
 40% {
   -ms-transform: scale(.7,.7) rotate(-5deg);
   transform: scale(.7,.7) rotate(-5deg);
 }
 50% {
   -ms-transform: scale(1.2,1.2) rotate(5deg);
   transform: scale(1.2,1.2) rotate(5deg);
 }
 60% {
   -ms-transform: scale(.8,.8) rotate(-5deg);
   transform: scale(.8,.8) rotate(-5deg);
 }
 70% {
   -ms-transform: scale(1.1,1.1) rotate(5deg);
   transform: scale(1.1,1.1) rotate(5deg);
 }
 80% {
   -ms-transform: scale(.9,.9) rotate(-5deg);
   transform: scale(.9,.9) rotate(-5deg);
 }
 90% {
   -ms-transform: scale(1,1) rotate(5deg);
   transform: scale(1,1) rotate(5deg);
 }
 100% {
   -ms-transform: rotate(0deg);
   transform: rotate(0deg);
 }

}

@-o-keyframes "bubbly" {
 0% {
   -o-transform: scale(1,1) rotate(0deg);
   transform: scale(1,1) rotate(0deg);
 }
 10% {
   -o-transform: rotate(5deg);
   transform: rotate(5deg);
 }
 20% {
   -o-transform: rotate(-5deg);
   transform: rotate(-5deg);
 }
 30% {
   -o-transform: rotate(5deg);
   transform: rotate(5deg);
 }
 40% {
   -o-transform: scale(.7,.7) rotate(-5deg);
   transform: scale(.7,.7) rotate(-5deg);
 }
 50% {
   -o-transform: scale(1.2,1.2) rotate(5deg);
   transform: scale(1.2,1.2) rotate(5deg);
 }
 60% {
   -o-transform: scale(.8,.8) rotate(-5deg);
   transform: scale(.8,.8) rotate(-5deg);
 }
 70% {
   -o-transform: scale(1.1,1.1) rotate(5deg);
   transform: scale(1.1,1.1) rotate(5deg);
 }
 80% {
   -o-transform: scale(.9,.9) rotate(-5deg);
   transform: scale(.9,.9) rotate(-5deg);
 }
 90% {
   -o-transform: scale(1,1) rotate(5deg);
   transform: scale(1,1) rotate(5deg);
 }
 100% {
   -o-transform: rotate(0deg);
   transform: rotate(0deg);
 }

}



</style>

app/views/posts/new.html.erb
<head>
	<%=javascript_include_tag 'jquery.js'%>
	<%=javascript_include_tag 'modernizr.js'%>
	
	<script>
		$(document).ready(function() {$("#dd").click(function(){
		

			if(!Modernizr.meter){
				alert('Sorry your brower does not support HTML5 progress bar');
			} else {
				var progressbar = $('#progressbar'),
					max = progressbar.attr('max'),
					time = (90/max)*5,	
			        value = progressbar.val();
			        var s="complete"

			    var loading = function() {
			        value += 1;
			        addValue = progressbar.val(value);
			        
			        $('.progress-value').html(value + '%');
			        if (value < max) {
			            progessbar();			           
			        }

			        if (value == max) {
			            clearInterval(animate);			           
			        }
			    };

			    var animate = setInterval(function() {
			        loading();
			    }, time);
			};
			});
			
		});
	</script></head>
<body>
<h1><u>Albums</u><h1>
<%=form_for @post,url: posts_path, :html => {:multipart => true} do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <%= f.fields_for :post_attachments do |p| %>
     <div class="field">
       <%= p.label :avatar %><br>
       
	</div></div>
       <%= p.file_field :avatar,:id=>"submitButton",:class=>"progress-button" %>
       <%= p.fields_for :tags do |k|%>
       <%= k.label :Tags%>
       <%= k.text_field :name,placeholder: "Tags separated with comma"%>
       <%end%>
     </div>
   <% end %>
  <p>
  	<div id="dd">
    <%= f.submit%>
    </div>
    <%= link_to 'Back', posts_path %>
  </p>

<% end %>

</body>
<div style="float: left; width: 350px;"><div class="demo-wrapper html5-progress-bar">
		<div class="progress-bar-wrapper">
			<progress id="progressbar" value="0" max="100"></progress>
			<span class="progress-value">0%</span>
			
		</div>
<style>
body{
    background-image: url("/assets/images36.jpeg");
   background-size: 800px 800px;
   
} 

</style>

app/views/posts/show.html.erb
<%=javascript_include_tag 'jquery.js'%>
	<%=javascript_include_tag 'modernizr.js'%>
	
	<script>
		$(document).ready(function() {$(".rab").click(function(e){
			 e.preventDefault();                   // prevent default anchor behavior
    var goTo = this.getAttribute("href"); // store anchor href

    // do something while timeOut ticks ... 

    
		

			if(!Modernizr.meter){
				alert('Sorry your brower does not support HTML5 progress bar');
			} else {
				var progressbar = $('#progressbar'),
					max = progressbar.attr('max'),
					time = (90/max)*5,	
			        value = progressbar.val();
			        var s="complete"

			    var loading = function() {
			        value += 1;
			        addValue = progressbar.val(value);
			        
			        $('.progress-value').html(value + '%');
			        if (value < max) {
			            progessbar();			           
			        }

			        if (value == max) {
			            clearInterval(animate);			           
			        }
			    };

			    var animate = setInterval(function() {
			        loading();
			    }, time);
			};
			setTimeout(function(){
         window.location = goTo;
    },3000);       
			});
		var url = $(this).attr("href");
		window.setTimeout(function(){document.location.href=url;}, time);
		});
	</script></head>
<body>
<p>
  <strong>Name:</strong>
  <%=@post.title %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>
<% @post_attachments.each do |p| %>
<div class="fish">
  <%= image_tag p.avatar_url,size: "160x100"%>
  <%= link_to "Download", post_attachment_path(p)%>
  <%= link_to "Download", p.avatar_url ,:class=>'rab'%>
  </div>
 
   <strong>Tags</strong>
   <%p.tags.each do|d|%>
   <%= link_to d.name,tag_path(d),:id=>'ff'%>
   <%end%>
  
 <%= link_to "Edit", edit_post_attachment_path(p) %>
  <%= button_to 'Delete', p, method: :delete,       
              data: { confirm: 'Are you sure?' } %>
             
<% end %>
<div style="float: left; width: 400px;"><div class="demo-wrapper html5-progress-bar">
		<div class="progress-bar-wrapper">
			<progress id="progressbar" value="0" max="100"></progress>
			<span class="progress-value">0%</span>
			
		</div>
<%= link_to 'Back', posts_path %>
<%= link_to 'show all tags', tags_path%>
</body>
<style>.fish
{
	background: white;
	display: inline;
	float: left;
	margin: 0 15px 30px;
	padding: 10px 10px 25px;
	text-align: center;
	text-decoration: none;
	-webkit-box-shadow: 0 4px 6px rgba(0, 0, 0, .3);
	-moz-box-shadow: 0 4px 6px rgba(0,0,0,.3);
	box-shadow: 0 4px 6px rgba(0,0,0,.3);
	-webkit-transition: all .15s linear;
	-moz-transition: all .15s linear;
	transition: all .15s linear;
	z-index:0;
        position:relative;
}
.fish:nth-child(2n)
{
	-webkit-transform: rotate(4deg);  
	-moz-transform: rotate(4deg); 
	transform: rotate(4deg); 
}
.fish:nth-child(3n) { 
	-webkit-transform: rotate(-24deg);  
	-moz-transform: rotate(-24deg); 
	transform: rotate(-24deg); 
}
.fish:nth-child(4n)
{
	-webkit-transform: rotate(14deg);  
	-moz-transform: rotate(14deg); 
	transform: rotate(14deg); 
}
.fish:nth-child(5n)
{
	-webkit-transform: rotate(-18deg);  
	-moz-transform: rotate(-18deg); 
	transform: rotate(-18deg); 
}
.fish:hover{
	-webkit-transform: rotate(0deg); 
	-moz-transform: rotate(0deg);
        transform: rotate(0deg);
	-webkit-transform: scale(1.2); 
	-moz-transform: scale(1.2);
        transform: scale(1.2);
	z-index:10;
	-webkit-box-shadow: 0 10px 20px rgba(0, 0, 0, .7);
	-moz-box-shadow: 0 10px 20px rgba(0,0,0,.7);
        box-shadow: 0 10px 20px rgba(0,0,0,.7);
}
.fish img { 
	display: block; 
	width: inherit; 
}
body {
    background-image: url(<%= @post_attachment.avatar_url %>);
   background-size: 1250px 850px;
   
} 


#ff {
    border: 2px solid #E0FFFF;
    background-color: #E0FFFF;
    color: #4B0082;
    text-decoration: none;
    margin : 10px;
    padding: 2px 2px 2px 2px;
    display: inline-block;
}
#ff:hover {
    border: 2px solid #E0FFFF;
    background-color:  	#FFB6C1;
}

</style>
<div id="container">
  <div id="butterfly">
    <div class="left wingg"></div>
    <div class="right wingg"></div>
    
  </div>
</div>
<style>


#container {
perspective: 600px;
perspective-origin: -20% 20%;
width: 850px;
height: 566px;
left: 300px;
top: 0px;
color: gray;
margin: 0px auto;
}

#butterfly {
 -webkit-animation: mymove 5s infinite; /* Chrome, Safari, Opera */
    animation: mymove 5s infinite;
transform: rotateZ(-30deg) rotate3d(0, 1, 0, 0deg) scale3d(0.5, 0.5, 0.5);
transform-origin: 51% 50%;
left: 0px;
top: 0px;
width: 400px;
height: 238px;
transform-style: preserve-3d;
/*Fly in a loop below*/
/*animation-name: butterflyani;
animation-duration: 5s;
animation-iteration-count: infinite;
animation-timing-function: linear;*/
}

.wingg {
transform: rotateX(30deg)  translate3d(-200px, 0px, 0px) rotate3d(0, 1, 0, 160deg);
transform-origin: top right;
position: absolute;
left: 200px;
top: 0px;
width: 200px;
height: 238px;
background: url(http://blueskyyogaohio.com/wp-content/themes/Chameleon/images/butterfly.png) no-repeat;
animation-name: rightwingani;
animation-duration: 0.6s;
animation-delay: 2s;
animation-iteration-count: infinite;
animation-timing-function: ease-out;
}

#butterfly .left{
transform: rotateX(30deg) rotate3d(0, 1, 0, 0deg);
animation-name: leftwingani;
left: 0px;
top: 0px;
}

@keyframes rightwingani {
	from {
		transform:rotateX(30deg) translate3d(-200px, 0px, 0px) rotate3d(0, 1, 0, 160deg);
	}
	50% {
		transform:rotateX(30deg) translate3d(-200px, 0px, 0px) rotate3d(0, 1, 0, 100deg);
	}
	to{
		transform:rotateX(30deg) translate3d(-200px, 0px, 0px) rotate3d(0, 1, 0, 160deg);
	}
}

@keyframes leftwingani {
	from {
		transform:rotateX(30deg) rotate3d(0, 1, 0, 0deg);
	}
	50% {
		transform:rotateX(30deg) rotate3d(0, 1, 0, 80deg);
	}
	to{
		transform:rotateX(30deg) rotate3d(0, 1, 0, 00deg);
	}
}





</style>